apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    run: nginx-pod
spec:
  containers:
    - name: nginx
      image: quay.io/mnara/nginx:1.20
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-pod
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod
  type: LoadBalancer
